### ISSUE TITLE
Live demo doesn't work anymore after 2.0.0+

### ISSUE THREAD

**Issue by Kykuy** [bpk68/g-sheets-api#103]
However, if you set the version to latest and provide the API key, everything is fine. I guess you could generate a separate API key and set it to work with Google Sheets API only for minimum hassle.
I could even "donate" one, I guess.

**Comment by bpk68** [comment]
Hey @Kykuy I'll get this sorted today. I've been on a bank holiday weekend here in the UK, but spotted this live demo issue on the release of v2.0 😬 

I'll get it updated with a burner API key of my own that's restricted to the CodeSandbox URL 👍🏻

Thanks for raising this.
