### ISSUE TITLE
Feature request: use sheetNumber for sheets with custom sheet names

### ISSUE THREAD

**Issue by adamjohnson** [bpk68/g-sheets-api#109]
Let's say you create a sheet with some data in it. The default sheet name is `Sheet1`. When using g-sheets-api, `sheetNumber: 1` works here.

Now, let's say you want to rename this sheet on Google Sheets. Let's rename it to `bpk68 is awesome!`.

Now, `sheetNumber: 1` no longer works.

Is it possible to allow `sheetNumber` to work when sheets have a custom name?

(and, yes, I realize `sheetName` exists)

_____________________________________________

Thanks for this awesome package. 💯  👍

**Comment by bpk68** [comment]
Hey Adam,

Thanks for the kind words, I'm so pleased you're finding the package useful. Given the potential to introduce a breaking change to how people are using the number vs name thing right now and the fact that both options area available for people to use, I'm going to mark this 'won't fix' to deprioritise it. 

I'm open to pull requests for budding contributors to lend a hand, but this enhancement isn't a priority for the package right now. 

If there's anything else you'd like to see in the package though, then I'm all ears and welcome open issues and enhancement suggestions.
