### ISSUE TITLE
add declaration file for support with typescript

### ISSUE THREAD

**Issue by ElasticBottle** [bpk68/g-sheets-api#113]
Hi, Just curious if there is any plans to support typescript as of now or any work arounds with the module declaration files?
![image](https://user-images.githubusercontent.com/44563205/150287782-7944fb5e-a262-45a6-a0ab-dcd2d4ce3680.png)

Thanks!

**Comment by bpk68** [comment]
Hey there, it's not on the roadmap as of yet, but I'll put it there and try to add a declaration file for it. 

If you end up writing one, by all means, submit it too and I can factor that in, but leave this with me and I'll take a look 👍🏻

**Comment by ElasticBottle** [comment]
Cool, thanks so much! Looking forward to it! Very handy little library otherwise?

**Comment by bpk68** [comment]
Sorry for the delay in this, it's been crazy over the past months, but I'm pleased to say `v2.1.3` has just been released this very moment and includes a few `d.ts` files for TS support. Hope that helps people out and many thanks for raising the requirement 👍🏻
