### ISSUE TITLE
Sheets Fetch URL

### ISSUE THREAD

**Issue by carrie2517** [bpk68/g-sheets-api#126]
When I add my SheetsID and APIKey to the link used in the project (https://sheets.googleapis.com/v4/spreadsheets/${sheetId}/values/${sheetNameStr}?dateTimeRenderOption=FORMATTED_STRING&majorDimension=ROWS&valueRenderOption=FORMATTED_VALUE&key=${apiKey}`)
I get this error
```
{
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "sheets.googleapis.com"
        }
      }
    ]
  }
}
```

The link that worked for me was this instead: https://sheets.googleapis.com/v4/spreadsheets/${sheetId}/values/${sheetNameStr}?valueRenderOption=FORMATTED_VALUE&key=${apiKey}

Is this actually an issue? Or am I missing some sort of set up?

**Comment by bpk68** [comment]
Hey @carrie2517, it's not something that's been raised before, nor is it something I've come across myself, but thanks for flagging it. 

I'll be adding support for TypeScript this month so I'll take a look at this at the same time and see if there's an underlying issue with the Sheets path that's called 👍🏻.

**Comment by bpk68** [comment]
Looking at the updated package (latest release is today v2.1.3) the main demo runs fine and loads the sheet data no problemo.

I'm going to close this, but any more problems, please open another issue and we'll look into it more.
