### ISSUE TITLE
Multiple filters operators (AND, OR)

### ISSUE THREAD

**Issue by crtlf** [bpk68/g-sheets-api#14]
Hi,

Thanks for the library, it's really useful.

When using multiple filters, it looks like you're fetching the datas that are validating at least one of the filter (like an `OR` operator). Is it possible to get the datas that validates ALL filters (like an `AND` operator) ?

---

Example :

| Name    	| Type      	| Color  	|
|---------	|-----------	|--------	|
| Kiwi 🥝     	| Fruit     	| Green  	|
| Banana 🍌   	| Fruit     	| Yellow 	|
| Broccoli 🥦 	| Vegetable 	| Green  	|

```javascript
const options = {
  sheetId: 'ID',
  filter: {
    'Type': 'Fruit',
    'Color': 'Green'
  }
}
```

I got :

* `Kiwi 🥝` because it's a fruit and green
* `Banana 🍌` because it's a fruit
* and `Broccoli 🥦` because it's green

while I only want the green fruit `Kiwi 🥝`.

---

Thank you

**Comment by crtlf** [comment]
If like me, you wish to use the filters with an `AND` operator, I suggest skipping the filter option and do it yourself after all the datas has been get.

It's surely not the best way, but I manage to make it work that way. I don't see a drop in performance of the script, as I have only ~100 results.

```javascript
var options = {
    sheetId: 'ID',
};

// Your custom filter
var filters = {
    'Type': 'Fruit',
    'Color': 'Green'
};

GSheetReader(options, results => {
    // For each filter
    for (let [key, value] of Object.entries(filters)) {
        // Loop through each result
        results.forEach(function(data, index) {
            // If a result does not have the specified value, delete it
            // e.g. `Type` !== `Fruit`
            if (data[key] !== value) {
                delete results[index];
            }
        });
    }
});
```

**Comment by bpk68** [comment]
Hi @crtlf 

Great suggestion! Not something I'd initial thought of, but so obvious!

I'll look at augmenting the filter option to include some sort of option. That'll allow you to supply either a 'OR' or a 'AND' clause. It'll still be fairly 'dumb' as a filter and this ends up being a very binary filter, but it's better than what it is right now and it'll help people get a little flexibility.

**Comment by bpk68** [comment]
@crtlf if you get 10 minutes, you can download the `filter-enhancements` branch and have a play with the changes to see if it suits your needs (and a more general filter ability). 

You can now supply a new `filterOptions` object along with the initial options that looks like this:

```
filterOptions: {
    operator: 'or', // can be 'or' or 'and'
    matching: 'loose' // can be 'loose' or 'strict'
}
```

I'm confident it's OK and it works on my local test cases, but I could do with a second set of eyes to make sure it's all fine and dandy.

**Comment by crtlf** [comment]
It's working on my project too 👍

I had a bigger project but we had to make it work server-side instead, because of a network restriction blocking all HTTP request from *.google.com, so I unfortunately cannot test on it.

Thank's for your time on this !

**Comment by bpk68** [comment]
Ahh nothing like network restrictions to block you 😄 

Thanks for having a look and I'll get this issue closed off as implemented
