### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by kosirm** [bpk68/g-sheets-api#151]
I'm out of ideas, I double checked everything, but no matter, what I do, I get this result:

`error: Failed to fetch from GSheets API. Check your Sheet Id and the public availability of your GSheet.`

Please help!

**Comment by bpk68** [comment]
Hey @kosirm apologies for the late response to this, could you add me as an editor to your Sheet please? You can add google@robkendal.co.uk to the Sheet and I'll see what's happening.

Could you also share the code that you're using to access the Sheet with via the package, please?

**Comment by bpk68** [comment]
Going to close this due to inactivity, but please re-open if you're still struggling and I'd be happy to help.
