### ISSUE TITLE
Can i have CDN link for this?

### ISSUE THREAD

**Issue by jitendra1607** [bpk68/g-sheets-api#16]
My app size increased after using this, I want to have CDN of this like others. This package is awesome.

**Comment by bpk68** [comment]
Hey @jitendra1607 

So pleased you like the package. 

So, you have a few options to consume this from a CDN. However, the one's I'd recommend initially are:

- JS Delivr - https://www.jsdelivr.com/package/npm/g-sheets-api
- and Unpkg - https://unpkg.com/

With Unpkg, you'll have to read the docs and build the URL, but it's fairly straightforward.

Happy Google Sheets-ing 😄
