### ISSUE TITLE
sheetNumber parameter does not seems to work

### ISSUE THREAD

**Issue by DevendraKumarL** [bpk68/g-sheets-api#23]
Forked your demo https://codesandbox.io/s/g-sheets-reader-demo-7ww3v?file=/src/index.js and I tried to fetch data from sheet 2 but it doesn't seem to work.

Even after updating to the latest version `1.2.0` I still see the URL is default using the first sheet - `nodes_modules/g-sheets-api/dist/gsheetsapi.js`: `var sheetsUrl = "https://spreadsheets.google.com/feeds/cells/".concat(sheetId, "/1/public/values?alt=json-in-script");`

Please help, I'm not able to understand what's wrong in the way I use this npm package.

**Comment by sc8696** [comment]
Looking at the code, the "sheetNumber" parameter just isn't used anywhere at all... so no wonder this isn't working.

**Comment by bpk68** [comment]
Hey @DevendraKumarL ,

Sorry about the problems with the sheet number and thank you to @sc8696 for pointing out the cause. 

In a classic rookie move (yes, they still happen to senior devs!), I'd gotten too excited about the latest release and actually pushed it before _building) it.... 🤦 

Anyway, I've pushed up a fix in v1.2.1, so if you upgrade to that, you'll be able to see it working. I've tested this solution locally and confirmed it in a CodeSandbox instance too, so you should be good to go.

Thanks for your patience and happy using!

**Comment by DevendraKumarL** [comment]
That's awesome! Thanks @bpk68
