### ISSUE TITLE
Add functionality to support Node-based instances

### ISSUE THREAD

**Issue by bpk68** [bpk68/g-sheets-api#24]
@DevendraKumarL raised an issue about the package not working when run in a Node environment/instance. 

It doesn't work because Node doesn't support the browser-based `fetch` mechanism which the g-sheets-api depends on to call the Sheet information. 

This isn't a bug or issue. However, it would be nice to support Node environments, so we could do with implementing Node-compatible support for fetching the information from Sheets.

**Comment by schlomo** [comment]
I solved this problem by installing [node-fetch](https://www.npmjs.com/package/node-fetch) and adding this before loading `g-sheets-api`:
```javascript
global.fetch = require('node-fetch');
```

Would be nice to add this info to the documentation.

**Comment by bpk68** [comment]
Top man, I actually added in a fix for this this morning. I'll be updating the documentation and pushing out a new release on Friday 😄

**Comment by DevendraKumarL** [comment]
@bpk68 Glad to know we will be having this fix!

**Comment by bpk68** [comment]
Documentation updated and support for Node (and Node fetch) is added. Released to NPM this morning as v1.3.0
