### ISSUE TITLE
does demo still work?

### ISSUE THREAD

**Issue by alirezagit** [bpk68/g-sheets-api#3]
Hi.
Thanks for sharing the code with us.
I try the demo you provided but it only comes up with loading...
does it still work?

I also get this error for line 1 in index.js
index.js:1 Uncaught SyntaxError: Cannot use import statement outside a module

**Comment by bpk68** [comment]
Hi @alirezagit , sorry for the delay in responding, it looks like I'm not getting notifications on this, which is annoying.

Yes, everything looks OK to me. I've checked out the repo and run `yarn start` and it fires up the demo at http://localhost:8080.

It could be a lot of things, but what I'd recommend is the following:

- Delete your `node_modules` folder
- Delete your `yarn.lock` file
- Run `yarn install` from your terminal
- Once that's finished, run `yarn start` 

Then, the demo should automatically run via Webpack.\

Let me know if you're still getting issues and we'll have another look. But I'll close this for now.
