### ISSUE TITLE
Error Handling?

### ISSUE THREAD

**Issue by YashTotale** [bpk68/g-sheets-api#41]
I've just started using this package and so far it's been working great. However, I'm not sure how I would be able to handle errors that occur when using the reader (for example, if the sheet-id is incorrect).

Is there a way to do this?

**Comment by bpk68** [comment]
Hey Yash, 

Thanks for raising the issue. I've added in some error handling into the latest release, v1.4.0. If you check the updated documentation, you'll find that you can either handle the error with a standard JS Promise `.catch()`block, or pass in a third argument which will be an error handling function of your own.
