### ISSUE TITLE
In browser demo

### ISSUE THREAD

**Issue by adamjohnson** [bpk68/g-sheets-api#46]
Would love to see a working demo of this package published either via [Github Pages](https://pages.github.com/) or something like [Codepen](https://codepen.io/)/[JSBin](http://jsbin.com/?html,output)/etc.

My projects don't include a module bundler like Webpack, so having an existing bundle (even if it was just on JSDelivr) would be really helpful.

Related to #16.

______________

Have to say, really enjoy the JSON output of this package compared to the Google Sheets API. Great work. 👏

**Comment by bpk68** [comment]
Hey Adam, 

Thanks for the kind words, really appreciated!

I've actually had a working demo sitting in a CodeSandbox for a while, but it's not been linked from the readme file. I've updated the readme file to include the demo link, but if you'd like to check it out, it's here >>> [https://codesandbox.io/s/g-sheets-reader-demo-qm5r0](https://codesandbox.io/s/g-sheets-reader-demo-qm5r0).

Hack it about all you like on there, and feel free to use the demo sheet that's included as that's just a publicly available link from my GDrive account.
