### ISSUE TITLE
breaking change in 1.4.1

### ISSUE THREAD

**Issue by vinnyang** [bpk68/g-sheets-api#71]
Hi there,
Found [THIS](https://github.com/bpk68/g-sheets-api/commit/205632902dfbd60c95ed25c00cd17d5b7494442c#diff-8343ac9fac314b7586e4d50f8b35c59a027a118e7c81fd0c24a86267ce2d3fd0L87) after I upgraded to the latest version, and kind of a breaking change as the keys go from all lowercase to their original casing in the sheet.

Not sure what reasoning behind the change is, but curious to know if there is a plan to revert/change that again soon? Or to make it configurable?

Thanks in advance, keep up the good work 👍

**Comment by bpk68** [comment]
Hey there, 

Thanks for the feedback and for raising an issue. In a classic developer move I'm going to cite the 'it works on my machine' line 😊

No, in all seriousness, I think this was reverted to prevent a casing issue. If you view the [CodeSandbox demo](https://codesandbox.io/s/g-sheets-reader-demo-qm5r0?file=/src/index.js) that features the latest version (1.4.1), it works great, **plus** you can change the casing of the 'department' filter column name between 'archaeology' or 'Archaeology' and the sheet loads.

Here's a view of the GSheet that the demo uses:

![image](https://user-images.githubusercontent.com/38687284/109326658-5cd2cb00-784f-11eb-85b2-3b89619fd356.png)

There's no plans to revert or change that again, but if I can help at all then do let me know 🙂 and thanks for using my little library.
