### ISSUE TITLE
Example Google Sheet cannot be accessed freely

### ISSUE THREAD

**Issue by Kykuy** [bpk68/g-sheets-api#91]
When I try to open your example sheet at
[](https://docs.google.com/spreadsheets/d/1_IpENDkoujmWr-B0M2ZVcyvgPQGeKwYxfHX_JYTDtRc/edit)
It returns an "Acess denied, contact sheet owner" page.

**Comment by bpk68** [comment]
Hey Kykuy,

Yes, this is intentional. For security reasons, I'm not going to grant access to the demo sheet on my personal Google account. However, I've just added a screenshot of the demo sheet to the repo's readme in case people want to recreate it themselves.

**Comment by Kykuy** [comment]
I mean it's tough to fully wrap my head around the readme examples without seeing the sheet in the first place. 
Anyways, what you did is a good compromise.
