### ISSUE TITLE
FYI - Known issue with GSheets public json URL

### ISSUE THREAD

**Issue by bpk68** [bpk68/g-sheets-api#97]
If you've been experiencing an issue with the g-sheets-api package when calling your sheet data, something like this:

```
Failed to fetch from GSheets API. Check your Sheet Id and the public availability of your GSheet.
```

This is an issue with Google Sheets and the provision of the JSON response. I've checked the latest release and the previous releases and it doesn't seem to be caused by the package, but the issue is cropping up periodically. 

I'm investigating, but it appears to be at the Google Sheets side, which occasionally throws 404 errors when requesting a JSON version of the Sheet cell data.

**Comment by chonghorizons** [comment]
I did some sleuthing and am not able to reliably generate the error in a browser. Sometimes it works (no 404). SOmetimes it gives me a 404.

via browser...
If I am logged in to my goole account via Chrome, it gives the 404 error **intermittently** when I try https://spreadsheets.google.com/feeds/cells/1_IpENDkoujmWr-B0M2ZVcyvgPQGeKwYxfHX_JYTDtRc/1/public/values?alt=json
Same if I try Safari.

Same if I go into incognito mode or private browsing.

**Comment by chonghorizons** [comment]
I do notice that Google is changing their security model a bit. When I try to edit or view the file, it requires me to login to google. That might be part of the error.

See https://support.google.com/drive/answer/10729743?p=update_drives_user&visit_id=637644764142807252-4120208825&rd=1

## How to recreate the login
1.  Go to incognito mode
2.  Verify you aren't logged into google (go to google.com)
3. go to https://docs.google.com/spreadsheets/d/1_IpENDkoujmWr-B0M2ZVcyvgPQGeKwYxfHX_JYTDtRc/view#gid=0
4. See that it asks you to log in.

**Comment by chonghorizons** [comment]
Posted a bug report (?) here: https://groups.google.com/g/google-spreadsheets-api/c/60-m_ojfAZE
This is the google spreadsheets support group.

**Comment by chonghorizons** [comment]
## FOR THE FUTURE
I did a little more digging and I think this is (1) a temporary glitch and (2) it relies on v3 of the API, which may be shut down.

The new way is to generate an API key and use the new version (v4) of endpoints. Furthermore, there may be some breaking changes in how things are formatted.

The new way of doing this seems to be as follows:
1. Go to Google Cloud Platform. Make an account if needed.
2. create a project if you are new
3. https://console.cloud.google.com/apis/credentials --> then create credentials, API Key.
4. Google Sheets API, have to **enable** for this account.
5. Then use the new formatting of the url: GET https://sheets.googleapis.com/v4/spreadsheets/spreadsheetId/values/Sheet1?key=API_KEY
6. See the v4 formatting at https://developers.google.com/sheets/api/guides/migration#retrieve_row_data. Compare to the v3 formatting

NOTES:
* Don't share the API KEY. If you do, anyone can use it and rack up charges against the key.
* You may also want to restrict the API key to certain websites originators (e.g., yourdomain.com). Then, the key can't be used by thiefDomain.com. See https://cloud.google.com/docs/authentication/api-keys
* An API KEY is needed even if you are accessing a public document  (sad). Also needed just to access your own documents
* You can use the API KEY to access public documents owned by others. (You don't need the document owner to generate the API KEY. It seems like the API KEY is to allow v4 access to the sheets API, not about any specific document).
* Note, the sheets are referenced by name now, and not by 1=first sheet, 2=second sheet

Example:
https://sheets.googleapis.com/v4/spreadsheets/1J-90AAPZa64AFpqATXi9DMXlBzLiAQ5gX0PiVpuoGtY/values/Sheet1?key=API_KEY
(this google Sheet is set to public view)

Result from the GET is:
`
{
  "range": "Sheet1!A1:Z1000",
  "majorDimension": "ROWS",
  "values": [
    [
      "Public Sample"
    ],
    [
      "123123"
    ],
    [
      "8888"
    ]
  ]
}
`

The return value is a lot cleaner to read and parse.
The file can be accessed and edited here:
https://docs.google.com/spreadsheets/d/1J-90AAPZa64AFpqATXi9DMXlBzLiAQ5gX0PiVpuoGtY/edit?usp=sharing

## Alternate way to get google sheet contents
Another option is to use the Publish to Web option and select CSV.
This doesn't require a key:
https://docs.google.com/spreadsheets/d/e/2PACX-1vTkCHOZXGAAoL4mMNQLUKfOKzLHCcf9XhdvQhV_cXOwgFWTWw4M-_L9SdkPJlNvYHwVvy4D_xqS5na9/pub?output=csv

Note: same file, but note that the spreadsheetId is no longer in the URL. It's a new Id that is linked.

https://support.google.com/docs/answer/183965?hl=en&co=GENIE.Platform%3DDesktop

**Comment by chonghorizons** [comment]
Update/FYI: If you restrict to API KEY to the Sheets API, there are no charges. Just rate-limiting in the free tier.

See https://apipheny.io/google-sheets-api/#google-sheets-api-pricing
https://developers.google.com/sheets/api/reference/limits
https://stackoverflow.com/questions/45225734/how-to-increase-google-sheets-v4-api-quota-limitations

Warning: By default API keys can be used for any API service, and some have charges beyond a free tier.

**Comment by jitendra1607** [comment]
Opening 'https://spreadsheets.google.com/feeds/cells/1_IpENDkoujmWr-B0M2ZVcyvgPQGeKwYxfHX_JYTDtRc/1/public/values?alt=json' in the new tab always giving proper result but not with g-sheet-api package.

**Comment by bpk68** [comment]
Hey all,

A huge, huge thanks for you all for contributing to this thread and the helpful links/suggestions. 

Unfortunately, it looks increasingly like this is a permanent issue caused by the mentioned shift by Google to their new v4 API. 

I've done some digging and looking at their docs, but it looks like there's zero support for the public accessing of a sheet's JSON data as was available in v3. This is a major problem for my humble little package here as it's very much dependant on this being available 😬.

The whole idea behind the `g-sheets-api` package was to allow really simple access and formatting of GSheets data _without_ the need for all the Google API and Sheets library stuff -- it's more faff than was needed for some simple data retrieval. 

However, I'm not sure how to move on with this really. There are two options as far as I can see:

1. Deprecate this package and point people towards v4 of the Google Sheets API.
2. Rework the package so that it deals with the new v4 API and includes my own API key.

In all honesty, I'm not sure of the merit of option 2 given that,

a) using my own API key may quickly hit the free limits (https://developers.google.com/sheets/api/reference/limits) which is around 100 requests per user per 100 seconds
b) the new API from Google is pretty easy and relatively simple to use so people may be better off using their own version.

Happy to discuss and open to thoughts, but, as sad as it is to shut down this helpful little package, it might be best to sunset it 😿

**Comment by jitendra1607** [comment]
Rework the package so that it deals with the new v4 API and includes user's API key.

**Comment by isaacxw** [comment]
Hey Rob,

Just want to preface by saying that I love your library and the work you have put into it. Like others have mentioned, I've been encountering 404 errors when trying to retrieve data from a google sheet but this thread has shed some light on this unfortunate event.

I second what @jitendra1607 said. If you have the capacity to update this package, you could provide an option for us to add our own API key to bypass the request limit. 

Would love to hear your thoughts on this. Thanks!

**Comment by bpk68** [comment]
Hey guys, 

Thanks for bearing with me. I've released v2.0.0 this morning after a large rewrite of the internals. The good news is that you shouldn't have to adjust your code as the results returned from the package are the same. How you call and access it (e.g. the options and such) again should be the same. 

There are two things you will need to do though:

1. You'll need to generate your own Google Sheets API Key and add this value to the `options` as `apiKey`.
2. You might need to update the sharing settings on your Sheet by going to 'Sharing' and then changing access to 'Anyone with the link can view'. 

If you check the updated `readme.md` then that details the process 👍🏻.

Any questions or issues with the update please let me know.

**Comment by jitendra1607** [comment]
> Hey guys,
> 
> Thanks for bearing with me. I've released v2.0.0 this morning after a large rewrite of the internals. The good news is that you shouldn't have to adjust your code as the results returned from the package are the same. How you call and access it (e.g. the options and such) again should be the same.
> 
> There are two things you will need to do though:
> 
> 1. You'll need to generate your own Google Sheets API Key and add this value to the `options` as `apiKey`.
> 2. You might need to update the sharing settings on your Sheet by going to 'Sharing' and then changing access to 'Anyone with the link can view'.
> 
> If you check the updated `readme.md` then that details the process 👍🏻.
> 
> Any questions or issues with the update please let me know.



> ## FOR THE FUTURE
> I did a little more digging and I think this is (1) a temporary glitch and (2) it relies on v3 of the API, which may be shut down.
> 
> The new way is to generate an API key and use the new version (v4) of endpoints. Furthermore, there may be some breaking changes in how things are formatted.
> 
> The new way of doing this seems to be as follows:
> 
> 1. Go to Google Cloud Platform. Make an account if needed.
> 2. create a project if you are new
> 3. https://console.cloud.google.com/apis/credentials --> then create credentials, API Key.
> 4. Google Sheets API, have to click **enable** for this account. Do it here: https://console.cloud.google.com/apis/api/sheets.googleapis.com/overview
> 5. Then use the new (v4) formatting of the url: GET https://sheets.googleapis.com/v4/spreadsheets/spreadsheetId/values/Sheet1?key=API_KEY
> 6. See the v4 formatting at https://developers.google.com/sheets/api/guides/migration#retrieve_row_data. Compare to the v3 formatting
> 
> NOTES:
> 
> * Don't share the API KEY. If you do, anyone can use it and rack up charges against the key.
> * If you use this on a website (front end), you may also want to restrict the API key to certain websites originators (e.g., yourdomain.com). Then, the key can't be used by thiefDomain.com and charge your account. See https://cloud.google.com/docs/authentication/api-keys
> * An API KEY is needed even if you are accessing a public document  (sad). Also needed just to access your own documents
> * You can use the API KEY to access public documents owned by others. (You don't need the document owner to generate the API KEY. It seems like the API KEY is to allow v4 access to the sheets API, not about any specific document).
> * Note, the sheets are referenced by name now, and not by 1=first sheet, 2=second sheet
> 
> Example:
> https://sheets.googleapis.com/v4/spreadsheets/1J-90AAPZa64AFpqATXi9DMXlBzLiAQ5gX0PiVpuoGtY/values/Sheet1?key=API_KEY
> (this google Sheet is set to public view)
> 
> Result from the GET is:
> `{ "range": "Sheet1!A1:Z1000", "majorDimension": "ROWS", "values": [ [ "Public Sample" ], [ "123123" ], [ "8888" ] ] }`
> 
> The return value is a lot cleaner to read and parse.
> The file can be accessed and edited here:
> https://docs.google.com/spreadsheets/d/1J-90AAPZa64AFpqATXi9DMXlBzLiAQ5gX0PiVpuoGtY/edit?usp=sharing
> 
> ## Alternate way to get google sheet contents
> Another option is to use the Publish to Web option and select CSV.
> This doesn't require a key:
> https://docs.google.com/spreadsheets/d/e/2PACX-1vTkCHOZXGAAoL4mMNQLUKfOKzLHCcf9XhdvQhV_cXOwgFWTWw4M-_L9SdkPJlNvYHwVvy4D_xqS5na9/pub?output=csv
> 
> Note: same file, but note that the spreadsheetId is no longer in the URL. It's a new Id that is linked.
> 
> https://support.google.com/docs/answer/183965?hl=en&co=GENIE.Platform%3DDesktop

@bpk68 Can we use the suggested alternate way to get data in CSV on the fly and convert it to JSON? This way we can bypass API key requirements.

**Comment by jitendra1607** [comment]
i have done this way, very easy, no API needed.

`axiosInstance
        .get(
          `https://docs.google.com/spreadsheets/d/e/2PACX-1vTkCHOZXGAAoL4mMNQLUKfOKzLHCcf9XhdvQhV_cXOwgFWTWw4M-_L9SdkPJlNvYHwVvy4D_xqS5na9/pub?output=csv`,
          { withCredentials: false }
        )
        .then(response => response.data)
        .then(data => {
          console.log(Papa.parse(data, { header: true }).data)
        })
        .catch(error => {
          console.log(error)
        })`

**Comment by declanramsay** [comment]
I'm getting the same error even though I've made the upgrade to 2.0.0, and included my API key in the options payload. I've also republished my sheet multiple times to see if that was the issue, and I have no issue pulling the data with my key direct from the v4 API.

Next 11.1.0
g-sheets-api 2.0.0

```jsx
import GSheetsReader from 'g-sheets-api';

export default async function getSheet(sheetId, sheetNumber = 1, options = {}) {
  let result;

  await GSheetsReader(
    {
      apiKey: process.env.NEXT_PUBLIC_GOOGLE_API_KEY,
      sheetId,
      sheetNumber,
      ...options,
    },
    (results) => {
      result = results;
    }
  );

  return result;
}
```

Returns 

```
Error: g-sheets-api error: Failed to fetch from GSheets API. Check your Sheet Id and the public availability of your GSheet.
```

**Comment by bpk68** [comment]
Update for y'all, 

Just released v2.1.0 this morning which adds support for custom sheet names. 

@declanramsay this might be your issue. If your underlying Sheet uses names instead of the default `Sheet1`, `Sheet2`, etc. then you can now add a `sheetName` string to the options object with the name of your Sheet that you want to pull data from. 
If not, then double-check that you've 'allowed anyone access who has this link' under the sharing options (it's an additional step needed, unfortunately 😭). 
If you're still not having any joy then please raise an issue and perhaps provide me a CodeSandbox or viewable thing where I can view the code and see what's happening. I hate pulling the 'it works on my machine', but testing looks great this end, so I think there's just that one thing that's amiss here, but we can sort it together 👍🏻 

@jitendra1607 if you open a separate issue for this I'll take a look when I have more time. It's not a priority for me right now, especially given how prone Google is to changing things, I'm not keen to do the work and have them remove the CSV access like they did the the JSON one. 
That said, if you want a crack at it yourself and open a PR then that would be hugely appreciated and I'd be happy to review that and merge it in 😊

**Comment by BonoboPower** [comment]
I have the same problem: 
"error: Failed to fetch from GSheets API. Check your Sheet Id and the public availability of your GSheet."

I see that in the Request URL there is an "undefined" like in screenshot...

<img width="1041" alt="Schermata 2021-08-24 alle 20 09 25" src="https://user-images.githubusercontent.com/19348782/130668112-0a9203e2-d8dc-4678-9fad-584bd0cd0e7d.png">

And the response has this kind of error:

<img width="501" alt="Schermata 2021-08-24 alle 20 14 11" src="https://user-images.githubusercontent.com/19348782/130668512-42571ed4-7898-4285-bcd4-4b5fd8c44b0a.png">

Maybe could be helpful

**Comment by wslyvh** [comment]
Just wanted to say thank you all who contributed and help create the v2 version! 🙌
