### ISSUE TITLE
Problem when renaming google sheet

### ISSUE THREAD

**Issue by piscogit** [bpk68/g-sheets-api#98]
Hi, 

Currently package logic assumes that all of the sheets has default google sheets provided names like : Sheet1, Sheet2...
But if someone rename the sheet then the logic breaks because its uses url that concatenate 'Sheet' with 
'options.sheetNumber'.

I propose that you add an optional 'options.sheetName' parameter that if provided will be prefered over the 'sheetNumber'.

Thanks anyway.

**Comment by bpk68** [comment]
Thanks for the suggestion @piscogit, this has been merged into `master` this morning and I'll get a release out to version 2.0.1 with this update in.
