### ISSUE TITLE
Unable to parse range: Sheet1

### ISSUE THREAD

**Issue by vinnyang** [bpk68/g-sheets-api#99]
Hi there,
I updated to the latest version, followed the README to create an API key, made the sheet accessible to every with the link, and it has always been published to the web (I turned that off and republished it again as a precaution while debugging this issue)

Code: 
```
const baseOption = {
    apiKey: process.env.API_KEY,
    sheetId: process.env.SHEET_ID,
    returnAllResults: true,
}

// ...
    try {
        await GSheetReader(
            {
                ...baseOption,
                sheetNumber: 1, 
            }
        )
    } catch (error) {
       // ...
    }
}

```

The call it makes: 
![Screen Shot 2021-08-21 at 9 17 46 PM](https://user-images.githubusercontent.com/199069/130339060-1d94c362-62dc-4422-821e-6a688c624d47.png)
It seems to plug in the sheetId and my api key correctly, but I got this…

Error:
![Screen Shot 2021-08-21 at 9 17 32 PM](https://user-images.githubusercontent.com/199069/130339063-39af060b-34ce-4e30-ae13-cd8760395bff.png)
Note: the sheet in a shared drive owned by the company, not a personal account. Not sure if this matters. 

Any idea how to fix this? Thanks in advance!!

**Comment by masun714** [comment]
I have the same problem before, I realised the request url Sheet1 is mapping the excel sheet name.
![image](https://user-images.githubusercontent.com/30792159/130346930-afce9b05-9c79-4d20-a375-32b793083d05.png)

**Comment by vinnyang** [comment]
Thanks for the reply! Mine has sheet name other than the default name, that's why I was having this issue. 

So I opened https://github.com/bpk68/g-sheets-api/pull/100. LMK what you think there, and if you're fine with that, I will updated the doc accordingly too.
